# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - name: Checkout current ref
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run the full build
      run: nix-build
    - run: npm publish --provenance --access public ${{github.workspace}}/result-2/*.tgz
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
